variable "environment" {
  description = "Environment name, for example dev or prod."
  type        = string
}

variable "location" {
  description = "Azure region."
  type        = string
}

variable "resource_prefix" {
  description = "Short lowercase resource prefix. Keep it compact because several Azure names are globally scoped."
  type        = string
}

variable "tags" {
  description = "Tags applied to all supported resources."
  type        = map(string)
  default     = {}
}

variable "tenant_id" {
  description = "Microsoft Entra tenant ID."
  type        = string
}

variable "create_resource_group" {
  description = "When true, create the workload resource group. When false, resource_group_name must already exist."
  type        = bool
  default     = true
}

variable "resource_group_name" {
  description = "Workload resource group name."
  type        = string
}

variable "internal_api_base_url" {
  description = "Internal REST API base URL for service-management-reference lookup."
  type        = string
}

variable "mail_shared_mailbox" {
  description = "Shared mailbox used as Graph sendMail sender."
  type        = string
}

variable "department_summary_mailbox" {
  description = "Department mailbox receiving completed scan summaries."
  type        = string
}

variable "webapp_public_base_url" {
  description = "Public Web App base URL used in notification links. Use the custom domain if one is configured."
  type        = string
}

variable "webapp_zip_path" {
  description = "Path to the ZIP package generated by scripts/build_deployment_artifacts.sh."
  type        = string
}

variable "automation_wheel_path" {
  description = "Path to the wheel generated by scripts/build_deployment_artifacts.sh."
  type        = string
}

variable "application_package_version" {
  description = "Version of the custom automation Python package."
  type        = string
  default     = "0.1.0"
}

variable "automation_dependency_packages" {
  description = "Optional Python3 package URLs for Azure Automation dependencies such as requests, azure-identity, azure-cosmos, azure-keyvault-secrets, fastapi, python-multipart, and uvicorn."
  type = map(object({
    content_uri     = string
    content_version = optional(string)
    hash_algorithm  = optional(string)
    hash_value      = optional(string)
  }))
  default = {}
}

variable "enable_cherwell" {
  description = "Enable Cherwell Change creation and status polling resources."
  type        = bool
  default     = false
}

variable "enable_graph_app_role_assignments" {
  description = "Create Microsoft Graph app role assignments for the managed identities."
  type        = bool
  default     = false
}

variable "cherwell_base_url" {
  description = "Cherwell REST API base URL."
  type        = string
  default     = ""
}

variable "cherwell_token_url" {
  description = "Cherwell OAuth token URL."
  type        = string
  default     = ""
}

variable "cherwell_client_id" {
  description = "Cherwell OAuth client ID."
  type        = string
  default     = ""
}

variable "cherwell_client_secret" {
  description = "Cherwell OAuth client secret. Stored in Key Vault when enable_cherwell is true and a value is supplied."
  type        = string
  default     = ""
  sensitive   = true
}

variable "cherwell_change_template_id" {
  description = "Cherwell Change template ID."
  type        = string
  default     = ""
}

variable "cherwell_completed_statuses" {
  description = "Comma-separated Cherwell statuses that count as completed."
  type        = string
  default     = "Closed,Completed,Resolved"
}

variable "expiry_window_days" {
  description = "Number of days ahead to detect expiring credentials."
  type        = number
  default     = 30
}

variable "cosmos_database_name" {
  description = "Cosmos DB SQL database name."
  type        = string
  default     = "credential-renewal"
}

variable "cosmos_cases_container_name" {
  description = "Cosmos DB container for credential cases."
  type        = string
  default     = "credential-renewal-cases"
}

variable "cosmos_overview_container_name" {
  description = "Cosmos DB container for App Registration overview records."
  type        = string
  default     = "credential-renewal-app-overview"
}

variable "cosmos_archive_container_name" {
  description = "Cosmos DB container for archive records."
  type        = string
  default     = "credential-renewal-archive"
}

variable "app_service_plan_sku" {
  description = "Linux App Service Plan SKU."
  type        = string
  default     = "P1v3"
}

variable "log_analytics_retention_days" {
  description = "Log Analytics retention in days."
  type        = number
  default     = 90
}

variable "scan_schedule" {
  description = "Azure Automation schedule for the scan runbook."
  type = object({
    frequency  = string
    interval   = number
    timezone   = string
    start_time = optional(string)
  })
  default = {
    frequency = "Day"
    interval  = 1
    timezone  = "Etc/UTC"
  }
}

variable "cherwell_status_schedule" {
  description = "Azure Automation schedule for Cherwell status polling."
  type = object({
    frequency  = string
    interval   = number
    timezone   = string
    start_time = optional(string)
  })
  default = {
    frequency = "Hour"
    interval  = 1
    timezone  = "Etc/UTC"
  }
}

variable "reporting_export_schedule" {
  description = "Azure Automation schedule for Log Analytics reporting export."
  type = object({
    frequency  = string
    interval   = number
    timezone   = string
    start_time = optional(string)
  })
  default = {
    frequency = "Hour"
    interval  = 1
    timezone  = "Etc/UTC"
  }
}

variable "automation_graph_app_roles" {
  description = "Microsoft Graph application roles assigned to the Automation managed identity when enabled."
  type        = set(string)
  default     = ["Application.Read.All", "User.Read.All", "Mail.Send"]
}

variable "webapp_graph_app_roles" {
  description = "Microsoft Graph application roles assigned to the Web App managed identity when enabled."
  type        = set(string)
  default     = ["Application.ReadWrite.All"]
}
